node {
    
    stage('SCM Checkout'){
    
        git 'https://github.com/Galatenea98/BACKEND_EXP.git'
    }
    stage('Compile-Packege'){
        def mvnHome = tool name: 'MAVEN_3_6_3', type: 'maven'
        sh "${mvnHome}HB-microservice-master/testing-bdd package"
    }
    
}
